### ISSUE TITLE
Remove all the version specific folders in root folder

### ISSUE THREAD

**Issue by jagan-jaya** [juspay/hyperswitch-helm#134]
Currently we are using GitHub Pages to maintain the versions of hyperswitch helm charts
1. https://juspay.github.io/hyperswitch-helm/v0.1.1/index.yaml
2. https://juspay.github.io/hyperswitch-helm/v0.1.2/index.yaml
3. https://juspay.github.io/hyperswitch-helm/v0.1.3/index.yaml
4. https://juspay.github.io/hyperswitch-helm/v0.2.0/index.yaml
5. https://juspay.github.io/hyperswitch-helm/v0.2.1/index.yaml

Above helps users to install different versions of the Helm charts. To achieve, we have the contents of each version in an [individual folder](https://github.com/juspay/hyperswitch-helm/tree/main/v0.1.1). But this won't scale if we start to publish more versions.
To solve this problem 

1. We need to remove those folders and build the zip files for each version and add them in the release assets. Eg: [loki](https://github.com/grafana/helm-charts/releases/tag/loki-distributed-0.80.1)
2. We need to index these assets in a single index.yaml for each version 
Eg: index.yaml
```
apiVersion: v1
entries:
  hyperswitch-stack:
  - apiVersion: v2
    appVersion: v1.6.1
    created: "2025-01-23T18:06:45.049550855Z"
    description: Hyperswitch-stack
    digest: 8b11c0912a1673b96224659869a4ddd987036cbdc6cb1f1ef7a199f85b31fefd
    name: hyperswitch
    type: application
    urls:
    - https://github.com/juspay/hyperswitch-helm/archive/refs/tags/hyperswitch-stack-v0.2.0.tar.gz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v1.5.1
    created: "2024-12-03T18:11:12.194810971Z"
    description: Hyperswitch-stack
    digest: 10fb88f219e05e0dea913731bea5862393ed1a10f072d723a0ac39e36b0bc819
    name: hyperswitch
    type: application
    urls:
    - https://github.com/juspay/hyperswitch-helm/archive/refs/tags/hyperswitch-stack-v0.1.3.tar.gz
    version: 0.1.3
```
